### ISSUE TITLE
Emailing Support

### ISSUE THREAD

**Issue by blaskovicz** [blaskovicz/MagicStick#12]
Right now we don't email for anything.

At a minimum, we should email when:
- [x] a user is added to a season (email the user, cc season owner)
- [x] a user is removed from a season (email the user, cc season owner)
- [x] a user is added to a match (email the user, cc season owner)
- [x] a user is removed from a match (email the user, cc season owner)
- [x] a match's status is reported (email match participants, cc season owner)
- [x] a user's account is created or updated (email user)
- [x] a season has a comment added (email season members)
- [x] add unsub group support per email category

Eventually, once match comments are added, we can email match members.

We also may want preferences for each of these email settings, but that can be done as a separate task.

**Comment by blaskovicz** [comment]
Also, we will want a way of just logging emails to stdout when `RACK_ENV` isn't `production`

**Comment by bheiskell** [comment]
https://addons.heroku.com/sendgrid?utm_campaign=category&utm_medium=dashboard&utm_source=addons

**Comment by bheiskell** [comment]
[SendGrid](https://addons.heroku.com/sendgrid?utm_campaign=category&utm_medium=dashboard&utm_source=addons) appears to be the most popular Heroku mail solution and it's free for 400 emails a day.

[Their tutorial](https://devcenter.heroku.com/articles/sendgrid#ruby-rails) for Ruby includes three options. ActionMailer (rails), Mail, and Pony. [Ruby Toolbox](https://www.ruby-toolbox.com/categories/e_mail#mail) suggests that the first two are the most popular.

[This tutorial](http://excid3.com/blog/using-actionmailer-without-rails/) makes it look pretty easy to get action mailer working. But the example for Mail seems even more simple. Both support a `:test` delivery method for development.

The real question is: do we want templates? If yes, I think ActionMail is the way to go.

I'm going to go ahead and configure the add-on to confirm it works first.

FYI @blaskovicz

**Comment by bheiskell** [comment]
I'm going to see if I can get ActionMailer going for the templates.

**Comment by bheiskell** [comment]
Using [this commit](https://github.com/bheiskell/MagicStick/commit/e5824b6a39d6d19458a6d2ac0dd1591d7d5e0bc2), you can now send mail via:

```ruby
    mail = Mailer.notification("ben.heiskell@gmail.com")  
    mail.deliver_now!                                     
```

We still need actual templates and variable substitution, but this should get us started. I need to read through [another tutorial](http://guides.rubyonrails.org/action_mailer_basics.html) to figure out how to actually use ActionMailer.

**Comment by blaskovicz** [comment]
@bheiskell as part of https://github.com/blaskovicz/MagicStick/commit/d3ec35feab5fb93030d34a80e0c04fa3e1b58452, I got emailing working for password reset.

**Comment by blaskovicz** [comment]
https://sendgrid.com/docs/API_Reference/SMTP_API/suppressions.html#-Defining-ASM-Groups-to-display-on-the-Manage-Preferences-page

should support email categories so we can do per-email-type unsubs (vs all emails)
