### ISSUE TITLE
Matchup display and data incorrect

### ISSUE THREAD

**Issue by Marshall-Hallenbeck** [blaskovicz/MagicStick#35]
I posted this in the comments but I finally received my 2FA code from GitHub so I'm filing an issue here.

For this week (6-7) I have 3 matchups all displayed in the matchups tab, but when I click on one of them , it shows a different person as the player (names blurred out since this is GitHub).

This is causing the "matches remaining" stat on the leaderboard to be incorrect too.

![magic-stick-match-messup](https://cloud.githubusercontent.com/assets/1518719/8059424/eea5e166-0e8d-11e5-835e-a31ce45d33fd.png)

**Comment by blaskovicz** [comment]
Derrick fixed this by changing match members. The match names currently have nothing to do with the players added to the matchup (although this may change in the future).

**Comment by Marshall-Hallenbeck** [comment]
Ah okay thanks :D I didn't noticed it was fixed in the leaderboard. Will the names be changed as well?
