### ISSUE TITLE
Data Storage

### ISSUE THREAD

**Issue by trescenzi** [blaskovicz/MagicStick#4]
Do we have any opinions on what we want to use to store user information? User accounts, decklists, tournament results and the like are going to need to be persisted. I'm fine with whatever but we should probably pick a technology and then stick with it before we start building out the other issues.

**Comment by blaskovicz** [comment]
I was just planning to spin up a postgres instance; we can just host our app on heroku and get one provisioned for us as well ( @bheiskell for confirmation ).

Once we have that, we can just use Sequelize or ActiveRecord to manage said databits.

**Comment by trescenzi** [comment]
Cool sounds good to me. Just wanted to make sure that whoever started building stuffs didn't all decide independently to use different databases lol.

**Comment by blaskovicz** [comment]
Yea, I figured that we'd need to do issue #1 before much else gets done.

This would give us the frontend and backend stubs along with the template for building it out.
