### ISSUE TITLE
User Profile

### ISSUE THREAD

**Issue by bheiskell** [blaskovicz/MagicStick#8]
Create a user profile page with the ability to update things like the avatar.

**Comment by bheiskell** [comment]
We'll rely on off-site hosting of avatars for the time being. E.g., I'm going to hotlink my github icon.

**Comment by blaskovicz** [comment]
You could also use gravatar; that's fairly common and most people have one already too.

**Comment by blaskovicz** [comment]
The user table has a `File :avatar` column for the avatar that I was eventually intending to use for the avatar (database blob).
